const fighters = [
  {
    id: 1,
    name: "Marcus King",
    nickname: "The Hammer",
    initials: "MK",
    weightClass: "Lightweight",
    fightingStyle: "Boxing / Wrestling",
    hometown: "Brooklyn, New York",
    imageClass: "fighter-image--marcus",
    demoFightAdded: false,
    fights: [
      {
        id: 101,
        opponent: "Darius Cole",
        result: "Win",
        method: "KO/TKO",
        round: 2,
        time: "3:42",
        event: "Combat Night 118",
        date: "2026-04-12",
        location: "New York, NY",
        notes: "Won after a counter right hand against the fence.",
      },
      {
        id: 102,
        opponent: "Andre Lewis",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Arena Clash 44",
        date: "2025-11-08",
        location: "Newark, NJ",
        notes: "Controlled the wrestling exchanges across three rounds.",
      },
      {
        id: 103,
        opponent: "Rico Santos",
        result: "Loss",
        method: "Submission",
        round: 1,
        time: "4:11",
        event: "Iron Circuit 21",
        date: "2025-06-20",
        location: "Philadelphia, PA",
        notes: "Caught in a rear-naked choke after a scramble.",
      },
      {
        id: 104,
        opponent: "Noah Briggs",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "2:05",
        event: "Harbor Fights 9",
        date: "2025-02-14",
        location: "Boston, MA",
        notes: "Finished with a short left hook in the pocket.",
      },
      {
        id: 105,
        opponent: "Felix Grant",
        result: "Win",
        method: "Decision - Split",
        round: 3,
        time: "5:00",
        event: "Metro Brawl 16",
        date: "2024-09-27",
        location: "Queens, NY",
        notes: "Close striking battle decided on the scorecards.",
      },
      {
        id: 106,
        opponent: "Omar Reed",
        result: "Win",
        method: "Submission",
        round: 2,
        time: "1:48",
        event: "Street Crown 7",
        date: "2024-04-05",
        location: "Brooklyn, NY",
        notes: "Locked in an arm-triangle after a takedown.",
      },
      {
        id: 107,
        opponent: "Chris Vale",
        result: "Draw",
        method: "Decision - Majority",
        round: 3,
        time: "5:00",
        event: "Night Circuit 33",
        date: "2023-12-02",
        location: "Hartford, CT",
        notes: "Even fight with neither athlete pulling clearly ahead.",
      },
      {
        id: 108,
        opponent: "Julian Park",
        result: "Win",
        method: "KO/TKO",
        round: 3,
        time: "0:57",
        event: "City Lights 12",
        date: "2023-07-18",
        location: "Manhattan, NY",
        notes: "Late-round pressure created the finish.",
      },
    ],
  },
  {
    id: 2,
    name: "Darius Cole",
    nickname: "Nightfall",
    initials: "DC",
    weightClass: "Welterweight",
    fightingStyle: "Kickboxing / Pressure",
    hometown: "Atlanta, Georgia",
    imageClass: "fighter-image--darius",
    demoFightAdded: false,
    fights: [
      {
        id: 201,
        opponent: "Marcus King",
        result: "Loss",
        method: "KO/TKO",
        round: 2,
        time: "3:42",
        event: "Combat Night 118",
        date: "2026-04-12",
        location: "New York, NY",
        notes: "Walked into a counter right hand while pressing forward.",
      },
      {
        id: 202,
        opponent: "Tyrell Boone",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "1:19",
        event: "Southern Strike 30",
        date: "2025-12-06",
        location: "Atlanta, GA",
        notes: "Ended the fight with a liver kick.",
      },
      {
        id: 203,
        opponent: "Hector Miles",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Crown Arena 19",
        date: "2025-08-22",
        location: "Charlotte, NC",
        notes: "Outworked Miles with leg kicks and cage control.",
      },
      {
        id: 204,
        opponent: "Lena Novak",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Crossroads 8",
        date: "2025-03-15",
        location: "Nashville, TN",
        notes: "Special catchweight bout decided by volume striking.",
      },
      {
        id: 205,
        opponent: "Ike Monroe",
        result: "Loss",
        method: "Submission",
        round: 2,
        time: "3:05",
        event: "Iron Circuit 18",
        date: "2024-10-11",
        location: "Birmingham, AL",
        notes: "Submitted with a guillotine after a failed takedown.",
      },
      {
        id: 206,
        opponent: "Ray Quinn",
        result: "Win",
        method: "KO/TKO",
        round: 2,
        time: "4:44",
        event: "Night Circuit 29",
        date: "2024-05-03",
        location: "Memphis, TN",
        notes: "Flurry of hooks forced the stoppage.",
      },
      {
        id: 207,
        opponent: "Sean Holt",
        result: "Win",
        method: "Submission",
        round: 1,
        time: "3:28",
        event: "Arena Clash 38",
        date: "2023-11-25",
        location: "Columbia, SC",
        notes: "Surprised Holt with a standing arm-triangle.",
      },
      {
        id: 208,
        opponent: "Devon Price",
        result: "Win",
        method: "Decision - Split",
        round: 3,
        time: "5:00",
        event: "Harbor Fights 4",
        date: "2023-06-09",
        location: "Savannah, GA",
        notes: "Close fight won with late-round aggression.",
      },
    ],
  },
  {
    id: 3,
    name: "Elena Torres",
    nickname: "Iron Rose",
    initials: "ET",
    weightClass: "Flyweight",
    fightingStyle: "Brazilian Jiu-Jitsu / Clinch",
    hometown: "San Antonio, Texas",
    imageClass: "fighter-image--elena",
    demoFightAdded: false,
    fights: [
      {
        id: 301,
        opponent: "Maya Brooks",
        result: "Win",
        method: "Submission",
        round: 3,
        time: "2:17",
        event: "Combat Night 116",
        date: "2026-02-28",
        location: "Houston, TX",
        notes: "Finished with an armbar after a scramble.",
      },
      {
        id: 302,
        opponent: "Lena Novak",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Arena Clash 43",
        date: "2025-10-17",
        location: "Dallas, TX",
        notes: "Controlled the clinch and scored timely takedowns.",
      },
      {
        id: 303,
        opponent: "Nina Vargas",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "4:02",
        event: "Southern Strike 28",
        date: "2025-05-24",
        location: "Austin, TX",
        notes: "Elbows from mount forced the stoppage.",
      },
      {
        id: 304,
        opponent: "Kara Ellis",
        result: "Loss",
        method: "Decision - Split",
        round: 3,
        time: "5:00",
        event: "Night Circuit 31",
        date: "2024-12-13",
        location: "San Antonio, TX",
        notes: "Came up short in a close striking contest.",
      },
      {
        id: 305,
        opponent: "Priya Shaw",
        result: "Win",
        method: "Submission",
        round: 2,
        time: "1:11",
        event: "Iron Circuit 17",
        date: "2024-07-19",
        location: "El Paso, TX",
        notes: "Quick triangle choke after a failed slam.",
      },
      {
        id: 306,
        opponent: "Rosa Kim",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "City Lights 14",
        date: "2024-01-26",
        location: "Phoenix, AZ",
        notes: "Steady pace and top control across fifteen minutes.",
      },
      {
        id: 307,
        opponent: "Ivy Stone",
        result: "Draw",
        method: "Decision - Majority",
        round: 3,
        time: "5:00",
        event: "Crossroads 5",
        date: "2023-08-11",
        location: "Albuquerque, NM",
        notes: "Even grappling battle ended in a draw.",
      },
      {
        id: 308,
        opponent: "Talia Brooks",
        result: "Win",
        method: "KO/TKO",
        round: 2,
        time: "0:44",
        event: "Harbor Fights 2",
        date: "2023-03-04",
        location: "Tucson, AZ",
        notes: "Uppercut on the break ended the fight early in round two.",
      },
    ],
  },
  {
    id: 4,
    name: "Maya Brooks",
    nickname: "The Storm",
    initials: "MB",
    weightClass: "Flyweight",
    fightingStyle: "Muay Thai / Scrambles",
    hometown: "Miami, Florida",
    imageClass: "fighter-image--maya",
    demoFightAdded: false,
    fights: [
      {
        id: 401,
        opponent: "Elena Torres",
        result: "Loss",
        method: "Submission",
        round: 3,
        time: "2:17",
        event: "Combat Night 116",
        date: "2026-02-28",
        location: "Houston, TX",
        notes: "Caught in an armbar while hunting for elbows.",
      },
      {
        id: 402,
        opponent: "Nina Vargas",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "2:51",
        event: "Arena Clash 42",
        date: "2025-09-12",
        location: "Miami, FL",
        notes: "Devastating left kick to the body.",
      },
      {
        id: 403,
        opponent: "Kara Ellis",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Southern Strike 27",
        date: "2025-04-18",
        location: "Tampa, FL",
        notes: "Outstruck Ellis with combinations and calf kicks.",
      },
      {
        id: 404,
        opponent: "Lena Novak",
        result: "Win",
        method: "Submission",
        round: 2,
        time: "4:33",
        event: "Night Circuit 30",
        date: "2024-11-01",
        location: "Orlando, FL",
        notes: "Rear-naked choke after a back take.",
      },
      {
        id: 405,
        opponent: "Priya Shaw",
        result: "Loss",
        method: "Decision - Split",
        round: 3,
        time: "5:00",
        event: "Iron Circuit 16",
        date: "2024-06-07",
        location: "Jacksonville, FL",
        notes: "Close fight that could have gone either way.",
      },
      {
        id: 406,
        opponent: "Rosa Kim",
        result: "Win",
        method: "KO/TKO",
        round: 3,
        time: "1:26",
        event: "City Lights 13",
        date: "2023-12-15",
        location: "Fort Lauderdale, FL",
        notes: "Late flurry forced the referee to intervene.",
      },
      {
        id: 407,
        opponent: "Ivy Stone",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Crossroads 4",
        date: "2023-07-28",
        location: "Tallahassee, FL",
        notes: "Clean striking and smart defense secured the win.",
      },
      {
        id: 408,
        opponent: "Talia Brooks",
        result: "Win",
        method: "Submission",
        round: 1,
        time: "3:09",
        event: "Harbor Fights 1",
        date: "2023-01-20",
        location: "Key West, FL",
        notes: "Armbar finish in the opening round.",
      },
    ],
  },
  {
    id: 5,
    name: "Andre Lewis",
    nickname: "The Titan",
    initials: "AL",
    weightClass: "Heavyweight",
    fightingStyle: "Power Striking / Wrestling",
    hometown: "Detroit, Michigan",
    imageClass: "fighter-image--andre",
    demoFightAdded: false,
    fights: [
      {
        id: 501,
        opponent: "Marcus King",
        result: "Loss",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Arena Clash 44",
        date: "2025-11-08",
        location: "Newark, NJ",
        notes: "Came up short against a lighter, more mobile opponent.",
      },
      {
        id: 502,
        opponent: "Bruno Hale",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "0:48",
        event: "Combat Night 114",
        date: "2025-07-04",
        location: "Detroit, MI",
        notes: "Overhand right ended the fight in under a minute.",
      },
      {
        id: 503,
        opponent: "Vince Carter",
        result: "Win",
        method: "KO/TKO",
        round: 2,
        time: "2:13",
        event: "Southern Strike 26",
        date: "2025-01-31",
        location: "Cleveland, OH",
        notes: "Ground-and-pound from mount forced the stoppage.",
      },
      {
        id: 504,
        opponent: "Omar Reed",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Night Circuit 28",
        date: "2024-08-16",
        location: "Chicago, IL",
        notes: "Used size and pressure to control the cage.",
      },
      {
        id: 505,
        opponent: "Ike Monroe",
        result: "Loss",
        method: "Submission",
        round: 1,
        time: "4:55",
        event: "Iron Circuit 15",
        date: "2024-03-22",
        location: "Indianapolis, IN",
        notes: "Caught in a heel hook late in round one.",
      },
      {
        id: 506,
        opponent: "Ray Quinn",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "3:17",
        event: "City Lights 11",
        date: "2023-10-06",
        location: "Milwaukee, WI",
        notes: "Left hook dropped Quinn along the fence.",
      },
      {
        id: 507,
        opponent: "Sean Holt",
        result: "Win",
        method: "Decision - Split",
        round: 3,
        time: "5:00",
        event: "Crossroads 3",
        date: "2023-05-12",
        location: "Columbus, OH",
        notes: "Tough striking war decided by the judges.",
      },
      {
        id: 508,
        opponent: "Devon Price",
        result: "Win",
        method: "Submission",
        round: 2,
        time: "2:40",
        event: "Harbor Fights 0",
        date: "2022-12-09",
        location: "Grand Rapids, MI",
        notes: "Keylock finish after a heavy slam.",
      },
    ],
  },
  {
    id: 6,
    name: "Lena Novak",
    nickname: "Black Ice",
    initials: "LN",
    weightClass: "Strawweight",
    fightingStyle: "Counter Striking / Grappling",
    hometown: "Chicago, Illinois",
    imageClass: "fighter-image--lena",
    demoFightAdded: false,
    fights: [
      {
        id: 601,
        opponent: "Elena Torres",
        result: "Loss",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Arena Clash 43",
        date: "2025-10-17",
        location: "Dallas, TX",
        notes: "Could not match Torres in the clinch exchanges.",
      },
      {
        id: 602,
        opponent: "Maya Brooks",
        result: "Loss",
        method: "Submission",
        round: 2,
        time: "4:33",
        event: "Night Circuit 30",
        date: "2024-11-01",
        location: "Orlando, FL",
        notes: "Tapped to a rear-naked choke.",
      },
      {
        id: 603,
        opponent: "Darius Cole",
        result: "Loss",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Crossroads 8",
        date: "2025-03-15",
        location: "Nashville, TN",
        notes: "Catchweight bout lost on volume and cage control.",
      },
      {
        id: 604,
        opponent: "Nina Vargas",
        result: "Win",
        method: "KO/TKO",
        round: 1,
        time: "1:55",
        event: "Combat Night 110",
        date: "2024-09-20",
        location: "Chicago, IL",
        notes: "Sharp counter left ended the fight quickly.",
      },
      {
        id: 605,
        opponent: "Kara Ellis",
        result: "Win",
        method: "Submission",
        round: 2,
        time: "3:14",
        event: "Southern Strike 24",
        date: "2024-02-02",
        location: "St. Louis, MO",
        notes: "Kimura finish from side control.",
      },
      {
        id: 606,
        opponent: "Priya Shaw",
        result: "Win",
        method: "Decision - Unanimous",
        round: 3,
        time: "5:00",
        event: "Iron Circuit 14",
        date: "2023-09-29",
        location: "Minneapolis, MN",
        notes: "Clean counters and timely takedown defense.",
      },
      {
        id: 607,
        opponent: "Rosa Kim",
        result: "Draw",
        method: "Decision - Majority",
        round: 3,
        time: "5:00",
        event: "City Lights 10",
        date: "2023-04-14",
        location: "Des Moines, IA",
        notes: "Competitive fight with little separation.",
      },
      {
        id: 608,
        opponent: "Ivy Stone",
        result: "Win",
        method: "KO/TKO",
        round: 3,
        time: "4:01",
        event: "Harbor Fights 3",
        date: "2022-11-18",
        location: "Milwaukee, WI",
        notes: "Late combination forced the stoppage.",
      },
    ],
  },
];
